### ISSUE TITLE
comentarios avances 3 y README

### ISSUE THREAD

**Issue by AliciaMstt** [JetsiMancilla/ProyectoFinalBioinf2017-II#2]
Bien dice una compañera que para calcular cuánto tiempo tomará algo en el laboratorio hay que tener un primer estimado, luego multiplicarlo por 2 y por último cambiar el orden de magnitud:

2 días = 4 semanas

Sobre tu README: puedes borrar la parte en español y dejar solo que está en inglés. Solo fíjate que esté bien formateado (en español pusiste en texto en negritas y en inglés no, etc). También te recomiendo que pongas viñetas a forma de lista en vez de explicarlo en todo el texto de corrido.

**Comment by JetsiMancilla** [comment]
Gracias!!
